### ISSUE TITLE
fails to build with `--locked`

### ISSUE THREAD

**Issue by ognevny** [lsd-rs/lsd#1024]
lockfile is not updated

**Comment by msfjarvis** [comment]
We've also hit this snag in [Nixpkgs](https://github.com/NixOS/nixpkgs) since the build system enforces that the `Cargo.lock` is not changed while building. It looks like that the v1.1.2 release only updated `version` in the Cargo.toml and not Cargo.lock, which is causing this: https://github.com/lsd-rs/lsd/compare/v1.1.1...v1.1.2

**Comment by msfjarvis** [comment]
This can be closed now, the issue is fixed and the CI should prevent it going forward.

**Comment by ognevny** [comment]
ok
