### ISSUE TITLE
Package for Debian and derivatives

### ISSUE THREAD

**Issue by jsj1027** [lsd-rs/lsd#303]
Could this be adding to the debian repos? So that people using things based on Debian can get this package? 

This would allow LSD to be install on Debian, Ubuntu, LinuxMint, Pop_Os, and many others, without installing the deb package directly or using the snap.

**Comment by Peltoche** [comment]
Hi @jsj1027,

It would be great to have inside on debian package but it's a complicated process to propose one and I don't really have the patience to do it. Most of the packages are not handled by myself and I hope that the debian package will be handle by someone knowing how to do it and with the time to update it.

If you are this person please feel free to propose the project for the debian package. You can find some `.deb` inside the release files.

**Comment by mickenordin** [comment]
I found it to be really easy to set up a debian repo hosted on github using reprepo, meaning I don't have to set up my own server for this. 

I have a cname set up for it so it is accessible from https://repo.mic.ke/debian and https works out of the box since github supports let's encrypt.

I have two packages that I distribute from https://github.com/mickenordin/repo

The projects that I distrubute from there are: https://github.com/mickenordin/wireguide and https://github.com/mickenordin/swayswitch and you can check for instance https://github.com/mickenordin/swayswitch/tree/main/packaging_scripts for how I do it, if you would like to set up a repo of your own. run.sh is the entry point.

Thank you for writing lsd, I use it every day :)

**Comment by 1000i100** [comment]
is it easyer to publish a ppa for it ?

**Comment by YDX-2147483647** [comment]
Years have passed… May I make a PR for a `curl | sh` way?

```shell
curl -sS https://webi.sh/lsd | sh
```

Install another binary to install lsd isn't a good idea, but what about a one-time script?

_Note_: The script fetches `lsd-*.tar.gz` from this repo. Please refer to their [src](https://github.com/webinstall/webi-installers/tree/main/lsd) or [FAQ](https://webinstall.dev/faq/#how-webi-works) for details.

---

Relevant:

- #401

  `curl | tar`, concerns about Windows.

- #627

  “`curl | bash`, or install using the `.deb` from release page.”

**Comment by zwpaper** [comment]
we have a installation method by `apt`

/close
