### ISSUE TITLE
[Bug]: user/group/filesize colors not changing with LS_COLORS

### ISSUE THREAD

**Issue by kassio** [lsd-rs/lsd#877]
### Version

- [X] latest

### version

lsd 0.23.1

### What OS are you seeing the problem on?

macOS

### installation

brew

### term

$ echo $TERM
wezterm

### What happened?

```markdown
It seems like user/group/filesize colors not changing with LS_COLORS
```

<img width="667" alt="image" src="https://github.com/lsd-rs/lsd/assets/120483/ebaf4640-5e34-4091-911a-e056811167ff">

### What expected?

```markdown
user/group/filesize to match colors of LS_COLORS
```

**Comment by davekch** [comment]
same on Ubuntu using `colors.yaml`. The colors do not change.

**Comment by zwpaper** [comment]
Hi @kassio @davekch please update to the v1.0.0 and try the `colors.yaml`.

if there is any problem, feel free to update it here.

**Comment by davekch** [comment]
forgot to mention, I am already using v1.0.0

I found out what my issue was: a nonexistent color somewhere in `colors.yaml`.
Interestingly, if *any* color is invalid, all other color settings also don't take effect. I could not change the color of `user` and `group`, because the color of something else was invalid.
Not sure whether that's a bug or intended. Maybe printing a warning would be helpful in such cases.

**Comment by zwpaper** [comment]
hi @davekch thanks for reporting, could you please post your invalid theme here?

I would find out where is the problem and may be do some improvement.

**Comment by kassio** [comment]
This worked for me. Thanks
